captainVersion: 4
services:
    $$cap_appname-unbound:
        restart: always
        environment:
            - TZ=${TZ}
        volumes:
            - /data/mail/hooks/unbound:/hooks
            - /data/mail/conf/unbound/unbound.conf:/etc/unbound/unbound.conf
        caproverExtra:
            image: mailcow/unbound:1.12
            notExposeAsWebApp: 'true'
    $$cap_appname-mysql:
        restart: always
        depends_on:
            - $$cap_appname-unbound
        environment:
            - TZ=${TZ}
            - MYSQL_ROOT_PASSWORD=${DBROOT}
            - MYSQL_DATABASE=${DBNAME}
            - MYSQL_USER=${DBUSER}
            - MYSQL_PASSWORD=${DBPASS}
            - MYSQL_INITDB_SKIP_TZINFO=1
        volumes:
            - /data/mail/hooks/unbound:/hooks
            - /data/mail/conf/unbound/unbound.conf:/etc/unbound/unbound.conf
        caproverExtra:
            image: mariadb:10.4
            notExposeAsWebApp: 'true'
caproverOneClickApp:
    variables:
        - description: HiptmairIT Registry Token, Used for error logging
          id: $$cap_registry_token
          label: Registry Token

        - description: Used for all environments
          defaultValue: srv-captain--mysql-db
          id: $$cap_mysql_host
          label: MySQL Hostname

        - description: Used for Prod Environment
          defaultValue: $$cap_appname
          id: $$cap_mysql_db_prod
          label: MySQL DB name (production)
        - description: Used for Prod Environment
          defaultValue: www
          id: $$cap_mysql_user_prod
          label: MySQL username (production)
        - description: Used for Prod Environment
          id: $$cap_mysql_password_prod
          label: MySQL password (production)
        - description: Used for Prod Environment
          defaultValue: 100
          id: $$cap_mysql_connection_limit_prod
          label: MySQL connection limit (production)

        - description: Used for Pilot Environment
          defaultValue: $$cap_appname_p
          id: $$cap_mysql_db_pilot
          label: MySQL DB name (pilot)
        - description: Used for Pilot Environment
          defaultValue: www
          id: $$cap_mysql_user_pilot
          label: MySQL username (pilot)
        - description: Used for Pilot Environment
          id: $$cap_mysql_password_pilot
          label: MySQL password (pilot)
        - description: Used for Pilot Environment
          defaultValue: 40
          id: $$cap_mysql_connection_limit_pilot
          label: MySQL connection limit (pilot)

        - description: Used for Development Environment
          defaultValue: $$cap_appname_d
          id: $$cap_mysql_db_dev
          label: MySQL DB name (dev)
        - description: Used for Development Environment
          defaultValue: www
          id: $$cap_mysql_user_dev
          label: MySQL username (dev)
        - description: Used for Development Environment
          id: $$cap_mysql_password_dev
          label: MySQL password (dev)
        - description: Used for Development Environment
          defaultValue: 10
          id: $$cap_mysql_connection_limit_dev
          label: MySQL connection limit (dev)

        - description: Used for authentication on dev/pilot
          id: $$cap_admin_basic_password
          label: Admin Basic Password
    instructions:
        start: >-
            This package can be used to prepare three containers for HiptmairIT Project Servers.
        end: >-
            Deployed Applications: 
            Production: $$cap_appname-prod.$$cap_root_domain
            Pilot: $$cap_appname-pilot.$$cap_root_domain
            Development: $$cap_appname-dev.$$cap_root_domain

            Todo: 
            - Enable WS-support
            - Create SSL-Certificate
            -
    displayName: HiptmairIT NODE-NG
    isOfficial: true
    description: This will create three NodeJS containers. You will need to create and configure the database information manually.
    documentation: Maintainer https://www.hiptmairit.at
